"""unique en comparaciones: emparejamiento contaminante ventana

Revision ID: b25c29569656
Revises: abdd7600fa23
Create Date: 2026-10-01 05:08:55.560073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25c29569656'
down_revision: Union[str, None] = 'abdd7600fa23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_comparaciones_emparejamiento_contaminante_ventana', 'comparaciones', ['emparejamiento_id', 'contaminante', 'ventana_inicio'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_comparaciones_emparejamiento_contaminante_ventana', 'comparaciones', type_='unique')
    # ### end Alembic commands ###
