"""esquema inicial AirE_Online

Revision ID: b8d5aefd9062
Revises: 
Create Date: 2026-09-28 20:36:37.715966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8d5aefd9062'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.Enum('openaq', 'aqicn', 'sisaire', name='ck_estaciones_fuente', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('id_externo', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('primera_vez_vista', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultima_vez_vista', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadatos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuente', 'id_externo', name='uq_estaciones_fuente_id_externo')
    )
    op.create_index('ix_estaciones_latitud_longitud', 'estaciones', ['latitud', 'longitud'], unique=False)
    op.create_table('emparejamientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estacion_a_id', sa.Integer(), nullable=False),
    sa.Column('estacion_b_id', sa.Integer(), nullable=False),
    sa.Column('distancia_km', sa.Float(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('estacion_a_id < estacion_b_id', name='ck_emparejamientos_orden_canonico'),
    sa.ForeignKeyConstraint(['estacion_a_id'], ['estaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estacion_b_id'], ['estaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estacion_a_id', 'estacion_b_id', name='uq_emparejamientos_par')
    )
    op.create_table('lecturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estacion_id', sa.Integer(), nullable=False),
    sa.Column('contaminante', sa.Enum('pm25', 'pm10', 'o3', 'no2', 'so2', 'co', 'aqi', name='ck_lecturas_contaminante', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('medido_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capturado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estacion_id'], ['estaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estacion_id', 'contaminante', 'medido_en', name='uq_lecturas_estacion_contaminante_medido_en')
    )
    op.create_index('ix_lecturas_contaminante_medido_en', 'lecturas', ['contaminante', 'medido_en'], unique=False)
    op.create_index('ix_lecturas_estacion_medido_en', 'lecturas', ['estacion_id', 'medido_en'], unique=False)
    op.create_table('pronosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.Enum('openaq', 'aqicn', 'sisaire', name='ck_pronosticos_fuente', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('estacion_id', sa.Integer(), nullable=False),
    sa.Column('contaminante', sa.Enum('pm25', 'pm10', 'o3', 'no2', 'so2', 'co', 'aqi', name='ck_pronosticos_contaminante', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('fecha_objetivo', sa.Date(), nullable=False),
    sa.Column('valor_promedio', sa.Float(), nullable=True),
    sa.Column('valor_min', sa.Float(), nullable=True),
    sa.Column('valor_max', sa.Float(), nullable=True),
    sa.Column('fecha_captura', sa.Date(), nullable=False),
    sa.Column('capturado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estacion_id'], ['estaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estacion_id', 'contaminante', 'fecha_objetivo', 'fecha_captura', name='uq_pronosticos_estacion_contaminante_objetivo_captura')
    )
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('umbral_aqi', 'discrepancia_fuentes', name='ck_alertas_tipo', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('severidad', sa.Enum('baja', 'media', 'alta', 'critica', name='ck_alertas_severidad', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('estado', sa.Enum('nueva', 'en_revision', 'notificada', 'normalizada', name='ck_alertas_estado', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('estacion_id', sa.Integer(), nullable=True),
    sa.Column('emparejamiento_id', sa.Integer(), nullable=True),
    sa.Column('contaminante', sa.Enum('pm25', 'pm10', 'o3', 'no2', 'so2', 'co', 'aqi', name='ck_alertas_contaminante', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('valor_disparador', sa.Float(), nullable=False),
    sa.Column('umbral', sa.Float(), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resuelta_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['emparejamiento_id'], ['emparejamientos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estacion_id'], ['estaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_alertas_abiertas', 'alertas', ['tipo', 'estacion_id', 'emparejamiento_id', 'contaminante'], unique=True, postgresql_where=sa.text("estado <> 'normalizada'"), postgresql_nulls_not_distinct=True)
    op.create_table('auditorias_pronostico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pronostico_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'resuelta', 'sin_datos', name='ck_auditorias_pronostico_estado', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('valor_real', sa.Float(), nullable=True),
    sa.Column('error_abs', sa.Float(), nullable=True),
    sa.Column('error_rel', sa.Float(), nullable=True),
    sa.Column('sesgo', sa.Float(), nullable=True),
    sa.Column('fuente_real', sa.Enum('openaq', 'aqicn', 'sisaire', name='ck_auditorias_pronostico_fuente_real', native_enum=False, create_constraint=True, length=30), nullable=True),
    sa.Column('estacion_real_id', sa.Integer(), nullable=True),
    sa.Column('distancia_km_real', sa.Float(), nullable=True),
    sa.Column('n_lecturas_real', sa.Integer(), nullable=True),
    sa.Column('resuelta_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estacion_real_id'], ['estaciones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pronostico_id'], ['pronosticos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pronostico_id', name='uq_auditorias_pronostico_pronostico_id')
    )
    op.create_index('ix_auditorias_pronostico_pendientes', 'auditorias_pronostico', ['pronostico_id'], unique=False, postgresql_where=sa.text("estado = 'pendiente'"))
    op.create_table('comparaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emparejamiento_id', sa.Integer(), nullable=False),
    sa.Column('contaminante', sa.Enum('pm25', 'pm10', 'o3', 'no2', 'so2', 'co', 'aqi', name='ck_comparaciones_contaminante', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('ventana_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ventana_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valor_a', sa.Float(), nullable=False),
    sa.Column('valor_b', sa.Float(), nullable=False),
    sa.Column('unidad_comun', sa.String(length=20), nullable=True),
    sa.Column('diferencia_abs', sa.Float(), nullable=False),
    sa.Column('calculada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['emparejamiento_id'], ['emparejamientos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparaciones')
    op.drop_index('ix_auditorias_pronostico_pendientes', table_name='auditorias_pronostico', postgresql_where=sa.text("estado = 'pendiente'"))
    op.drop_table('auditorias_pronostico')
    op.drop_index('uq_alertas_abiertas', table_name='alertas', postgresql_where=sa.text("estado <> 'normalizada'"), postgresql_nulls_not_distinct=True)
    op.drop_table('alertas')
    op.drop_table('pronosticos')
    op.drop_index('ix_lecturas_estacion_medido_en', table_name='lecturas')
    op.drop_index('ix_lecturas_contaminante_medido_en', table_name='lecturas')
    op.drop_table('lecturas')
    op.drop_table('emparejamientos')
    op.drop_index('ix_estaciones_latitud_longitud', table_name='estaciones')
    op.drop_table('estaciones')
    # ### end Alembic commands ###
